# 사이트 제목 및 설명
title: 지하철빌런위키
description: 이것은 GitHub Pages를 사용하여 만든 나의 위키입니다.

# 사이트 기본 URL (필요한 경우 설정)
# url: "" # 커스텀 도메인을 사용하는 경우
baseurl: "" # 프로젝트의 하위 경로가 있을 경우 (예: /blog)

# 빌드 설정
markdown: kramdown
theme: minima # 사용할 Jekyll 테마

# 사이트 저자 정보
author:kdy
  name: 당신의 이름
  email:kdywkrrk@gmail.com

# 빌드 후 제외할 파일이나 폴더
exclude:
  - README.md
  - LICENSE

# 소셜 미디어 정보 (선택 사항)
twitter_username: yourusername
github_username:  yourusername

# 플러그인 (GitHub Pages에서 사용 가능한 플러그인만)
plugins:
  - jekyll-feed

# 기타 Jekyll 설정
permalink: /:categories/:title/
